name: Single-Package CI Build and Linting

on:
  push:
    branches: 
      - develop
      - patch/*
      - prep-release/*
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches:
      - develop
      - patch/*
      - prep-release/*

  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:
    inputs:
      caller_event_name:
        type: string
        default: 'schedule'
        description: "Enter 'pull_request' (without quotes) to compare linting results to previous linting results."

jobs:
  build_develop_dispatch:
    name: Build against the development release
    uses: DUNE-DAQ/.github/.github/workflows/dunedaq-develop-cpp-ci.yml@develop
    with:
      caller_event_name: ${{ github.event.inputs.caller_event_name || github.event_name }}